import { CommonModule } from '@angular/common';
import { Component, Input, OnInit, inject } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { RouterLink } from '@angular/router';
import { finalize } from 'rxjs';
import { API_ENDPOINTS as API } from '../../../core/constants/api-endpoints';
import { ApiService } from '../../../core/services/api.service';
import { LanguageService } from '../../../core/services/language.service';

type Row = any;
type Section = 'dashboard'|'users'|'consultations'|'articles'|'services'|'homepage'|'settings'|'notifications';
type Column = { key: string; label: string };

@Component({
  selector: 'app-admin-resource-page', standalone: true, imports: [CommonModule, ReactiveFormsModule, RouterLink],
  template: `
    <div class="page-heading"><div><small class="eyebrow">{{title.toUpperCase()}}</small><h1>{{title}}</h1><p class="muted">{{description}}</p></div>
      <div class="heading-actions" *ngIf="!createMode && !editorMode && (section==='articles'||section==='services')"><button class="primary-button" (click)="startCreate()">＋ {{label('add')}}</button></div>
    </div>
    <ng-container *ngIf="section==='dashboard'"><section class="welcome-band"><div><small>{{i18n.t('brand.name')}}</small><h2>{{i18n.t('dashboard.greeting')}} {{userName}}</h2><p>{{i18n.t('dashboard.today')}}</p></div><a [routerLink]="link('admin/consultations')">{{i18n.t('dashboard.review')}} <span>←</span></a></section><div class="stat-grid"><article class="stat-card" *ngFor="let card of stats"><small>{{card.label}}</small><strong>{{card.value}}</strong><span>{{card.note}}</span></article></div></ng-container>

    <section class="content-panel" *ngIf="section==='dashboard'||(section!=='homepage'&&section!=='settings'&&section!=='notifications'&&!createMode&&!editorMode)">
      <div class="panel-heading" *ngIf="section==='dashboard'"><div><h2>{{i18n.t('dashboard.recent')}}</h2><p>{{i18n.t('dashboard.recentSub')}}</p></div><button class="secondary-button" (click)="load()">{{i18n.t('action.refresh')}}</button></div>
      <div class="toolbar" *ngIf="section!=='dashboard'"><input *ngIf="section==='articles'||section==='users'||section==='services'" [formControl]="search" [placeholder]="label('search')"><span class="toolbar-spacer"></span><button class="secondary-button" (click)="load()">{{i18n.t('action.refresh')}}</button></div>
      <div *ngIf="loading" class="state">{{i18n.t('common.loading')}}</div><div *ngIf="error" class="state error-text" role="alert">{{error}}</div>
      <div *ngIf="!loading&&!rows.length&&!error" class="state empty-state"><span class="empty-mark">○</span><strong>{{i18n.t('common.nothing')}}</strong><p>{{i18n.t('common.empty')}}</p><button *ngIf="section==='services'||section==='articles'" class="primary-button" (click)="startCreate()">＋ {{label('add')}}</button></div>
      <div class="table-wrap" *ngIf="!loading&&rows.length"><table><thead><tr><th *ngFor="let column of columns">{{column.label}}</th><th *ngIf="section==='users'||section==='services'||section==='articles'">{{i18n.t('column.actions')}}</th></tr></thead><tbody><tr *ngFor="let row of rows"><td *ngFor="let column of columns"><strong *ngIf="column.key==='name'||column.key==='title'">{{display(row,column.key)}}</strong><span *ngIf="column.key!=='name'&&column.key!=='title'">{{display(row,column.key)}}</span><small *ngIf="column.key==='name'">{{row['email']||row['phone']}}</small></td>
        <td *ngIf="section==='users'||section==='services'||section==='articles'" class="actions-cell"><button class="row-action" (click)="view(row)">{{label('view')}}</button><button class="row-action" *ngIf="section==='users'||section==='services'||section==='articles'" (click)="toggle(row)">{{section==='articles'?label('status'):i18n.t(row['isActive']===false?'action.activate':'action.deactivate')}}</button><button class="row-action" *ngIf="section==='services'||section==='articles'" (click)="edit(row)">{{label('edit')}}</button><button class="row-action danger-action" (click)="pendingDelete=row">{{i18n.t('action.delete')}}</button></td></tr></tbody></table></div>
      <div class="confirm-strip" *ngIf="pendingDelete"><span>{{label('confirmDelete')}}</span><button class="secondary-button" (click)="pendingDelete=null">{{i18n.t('action.cancel')}}</button><button class="primary-button" (click)="confirmDelete()">{{i18n.t('action.confirmDelete')}}</button></div>
      <div class="pagination" *ngIf="pagination"><span>{{pagination.total}} {{i18n.t('common.records')}} · {{i18n.t('common.page')}} {{pagination.page}} {{i18n.t('common.of')}} {{pagination.totalPages}}</span><div><button class="secondary-button" [disabled]="pagination.page<=1" (click)="page(-1)">{{i18n.t('action.previous')}}</button><button class="secondary-button" [disabled]="pagination.page>=pagination.totalPages" (click)="page(1)">{{i18n.t('action.next')}}</button></div></div>
    </section>

    <section class="content-panel editor-panel" *ngIf="(section==='services'||section==='articles')&&(createMode||editorMode)"><div class="panel-heading"><div><h2>{{editorMode==='view'?label('view'):editorMode==='edit'?label('edit'):label('add')}} {{title}}</h2><p>{{label('bilingualHelp')}}</p></div><button class="secondary-button" (click)="cancelEditor()">{{label('back')}}</button></div>
      <form [formGroup]="recordForm" (ngSubmit)="saveRecord()"><div class="language-fields"><fieldset><legend>{{i18n.t('article.english')}}</legend><label>{{label('title')}}<input formControlName="titleEn" [readonly]="editorMode==='view'"></label><label *ngIf="section==='services'">{{label('shortDescription')}}<textarea rows="2" formControlName="summaryEn" [readonly]="editorMode==='view'"></textarea></label><label *ngIf="section==='articles'">{{label('excerpt')}}<textarea rows="2" formControlName="summaryEn" [readonly]="editorMode==='view'"></textarea></label><label>{{label('description')}}<textarea rows="7" formControlName="descriptionEn" [readonly]="editorMode==='view'"></textarea></label><label>{{label('category')}}<input formControlName="categoryEn" [readonly]="editorMode==='view'"></label></fieldset>
        <fieldset dir="rtl"><legend>{{i18n.t('article.arabic')}}</legend><label>{{label('title')}}<input formControlName="titleAr" [readonly]="editorMode==='view'"></label><label *ngIf="section==='services'">{{label('shortDescription')}}<textarea rows="2" formControlName="summaryAr" [readonly]="editorMode==='view'"></textarea></label><label *ngIf="section==='articles'">{{label('excerpt')}}<textarea rows="2" formControlName="summaryAr" [readonly]="editorMode==='view'"></textarea></label><label>{{label('description')}}<textarea rows="7" formControlName="descriptionAr" [readonly]="editorMode==='view'"></textarea></label><label>{{label('category')}}<input formControlName="categoryAr" [readonly]="editorMode==='view'"></label></fieldset></div>
        <label *ngIf="section==='services'">{{label('order')}}<input type="number" formControlName="order" [readonly]="editorMode==='view'"></label><label *ngIf="section==='articles'">{{label('status')}}<select formControlName="status"><option value="draft">{{i18n.t('article.draft')}}</option><option value="published">{{i18n.t('article.published')}}</option><option value="archived">Archived</option></select></label><label *ngIf="section==='services'" class="check-label"><input type="checkbox" formControlName="isActive">{{label('active')}}</label>
        <label *ngIf="editorMode!=='view'">{{label('image')}}<input type="file" accept="image/*" (change)="selectImage($event)"></label><p *ngIf="imageUrl" class="muted">{{label('currentImage')}} <a [href]="imageUrl" target="_blank" rel="noopener">{{label('view')}}</a></p><div class="form-error" *ngIf="error">{{error}}</div><div class="form-actions"><button type="button" class="secondary-button" (click)="cancelEditor()">{{label('cancel')}}</button><button *ngIf="editorMode!=='view'" class="primary-button" [disabled]="saving||recordForm.invalid">{{saving?label('saving'):label('save')}}</button></div>
      </form>
    </section>

    <section class="content-panel editor-panel" *ngIf="section==='homepage'"><div class="panel-heading"><div><h2>{{i18n.t('home.contentTitle')}}</h2><p>{{i18n.t('home.bilingualHelp')}}</p></div><button class="secondary-button" (click)="loadDetail()">{{i18n.t('action.refresh')}}</button></div><div *ngIf="loading" class="state">{{i18n.t('common.loading')}}</div><form *ngIf="!loading" [formGroup]="homepageForm" (ngSubmit)="saveSingleton('homepage')"><h3>{{label('hero')}}</h3><div class="language-fields"><fieldset><legend>{{i18n.t('article.english')}}</legend><label>{{label('title')}}<input formControlName="heroTitleEn"></label><label>{{label('subtitle')}}<textarea rows="3" formControlName="heroSubtitleEn"></textarea></label><label>{{label('buttonText')}}<input formControlName="heroButtonEn"></label></fieldset><fieldset dir="rtl"><legend>{{i18n.t('article.arabic')}}</legend><label>{{label('title')}}<input formControlName="heroTitleAr"></label><label>{{label('subtitle')}}<textarea rows="3" formControlName="heroSubtitleAr"></textarea></label><label>{{label('buttonText')}}<input formControlName="heroButtonAr"></label></fieldset></div><label>{{label('buttonLink')}}<input formControlName="heroLink"></label><h3>{{label('about')}}</h3><div class="language-fields"><fieldset><legend>{{i18n.t('article.english')}}</legend><label>{{label('title')}}<input formControlName="aboutTitleEn"></label><label>{{label('description')}}<textarea rows="4" formControlName="aboutDescriptionEn"></textarea></label></fieldset><fieldset dir="rtl"><legend>{{i18n.t('article.arabic')}}</legend><label>{{label('title')}}<input formControlName="aboutTitleAr"></label><label>{{label('description')}}<textarea rows="4" formControlName="aboutDescriptionAr"></textarea></label></fieldset></div><h3>{{label('cta')}}</h3><div class="language-fields"><fieldset><legend>{{i18n.t('article.english')}}</legend><label>{{label('title')}}<input formControlName="ctaTitleEn"></label><label>{{label('description')}}<textarea rows="3" formControlName="ctaDescriptionEn"></textarea></label><label>{{label('buttonText')}}<input formControlName="ctaButtonEn"></label></fieldset><fieldset dir="rtl"><legend>{{i18n.t('article.arabic')}}</legend><label>{{label('title')}}<input formControlName="ctaTitleAr"></label><label>{{label('description')}}<textarea rows="3" formControlName="ctaDescriptionAr"></textarea></label><label>{{label('buttonText')}}<input formControlName="ctaButtonAr"></label></fieldset></div><div class="language-fields"><label>{{label('ctaLink')}}<input formControlName="ctaLink"></label><label>{{label('featuredServices')}}<input formControlName="featuredServices" [placeholder]="label('serviceIdsHint')"></label></div><div class="form-error" *ngIf="error">{{error}}</div><button class="primary-button" [disabled]="saving">{{saving?label('saving'):label('save')}}</button></form></section>

    <section class="content-panel editor-panel" *ngIf="section==='settings'"><div class="panel-heading"><div><h2>{{i18n.t('settings.contentTitle')}}</h2><p>{{i18n.t('settings.help')}}</p></div><button class="secondary-button" (click)="loadDetail()">{{i18n.t('action.refresh')}}</button></div><div *ngIf="loading" class="state">{{i18n.t('common.loading')}}</div><form *ngIf="!loading" [formGroup]="settingsForm" (ngSubmit)="saveSingleton('settings')"><h3>{{label('siteIdentity')}}</h3><div class="language-fields"><label>{{label('siteNameEn')}}<input formControlName="siteNameEn"></label><label dir="rtl">{{label('siteNameAr')}}<input formControlName="siteNameAr"></label></div><h3>{{label('contactDetails')}}</h3><div class="language-fields"><label>{{label('addressEn')}}<textarea rows="2" formControlName="addressEn"></textarea></label><label dir="rtl">{{label('addressAr')}}<textarea rows="2" formControlName="addressAr"></textarea></label></div><div class="language-fields"><label>{{label('email')}}<input type="email" formControlName="email"></label><label>{{label('whatsapp')}}<input formControlName="whatsapp"></label></div><label>{{label('phonesJson')}}<textarea rows="4" formControlName="phonesJson"></textarea></label><label>{{label('workingHoursJson')}}<textarea rows="5" formControlName="hoursJson"></textarea></label><label>{{label('socialLinksJson')}}<textarea rows="5" formControlName="socialJson"></textarea></label><h3>{{label('seo')}}</h3><div class="language-fields"><fieldset><legend>{{i18n.t('article.english')}}</legend><label>{{label('seoTitle')}}<input formControlName="seoTitleEn"></label><label>{{label('seoDescription')}}<textarea rows="3" formControlName="seoDescriptionEn"></textarea></label></fieldset><fieldset dir="rtl"><legend>{{i18n.t('article.arabic')}}</legend><label>{{label('seoTitle')}}<input formControlName="seoTitleAr"></label><label>{{label('seoDescription')}}<textarea rows="3" formControlName="seoDescriptionAr"></textarea></label></fieldset></div><div class="form-error" *ngIf="error">{{error}}</div><button class="primary-button" [disabled]="saving">{{saving?label('saving'):label('save')}}</button></form></section>

    <section class="content-panel" *ngIf="section==='notifications'"><div class="panel-heading"><div><h2>{{i18n.t('notice.title')}}</h2><p>{{i18n.t('notice.subtitle')}}</p></div><button class="secondary-button" (click)="markAll()">{{i18n.t('notice.markAll')}}</button></div><article class="notice-row" *ngFor="let item of notifications"><div class="notice-dot" [class.read]="item['isRead']"></div><div><strong>{{item['title']}}</strong><p>{{item['message']}}</p><small>{{item['createdAt']}}</small></div><button *ngIf="!item['isRead']" class="row-action" (click)="read(item)">{{i18n.t('notice.markRead')}}</button></article><div class="state" *ngIf="!notifications.length">{{i18n.t('notice.noItems')}}</div></section>`
})
export class AdminResourcePageComponent implements OnInit {
  @Input({ required: true }) section!: Section;
  @Input() createMode = false;
  readonly i18n=inject(LanguageService); private readonly api=inject(ApiService); private readonly fb=inject(FormBuilder); private readonly router=inject(Router);
  loading=false; saving=false; error=''; rows:Row[]=[]; notifications:Row[]=[]; pendingDelete:Row|null=null; pageNumber=1; editorMode:''|'create'|'edit'|'view'=''; editId=''; image:File|null=null; imageUrl='';
  pagination:{page:number;total:number;totalPages:number}|null=null;
  readonly search=this.fb.control('');
  readonly recordForm=this.fb.group({titleEn:['',[Validators.required]],titleAr:['',[Validators.required]],summaryEn:[''],summaryAr:[''],descriptionEn:[''],descriptionAr:[''],categoryEn:[''],categoryAr:[''],order:[0],isActive:[true],status:['draft']});
  readonly homepageForm=this.fb.group({heroTitleEn:[''],heroTitleAr:[''],heroSubtitleEn:[''],heroSubtitleAr:[''],heroButtonEn:[''],heroButtonAr:[''],heroLink:[''],aboutTitleEn:[''],aboutTitleAr:[''],aboutDescriptionEn:[''],aboutDescriptionAr:[''],ctaTitleEn:[''],ctaTitleAr:[''],ctaDescriptionEn:[''],ctaDescriptionAr:[''],ctaButtonEn:[''],ctaButtonAr:[''],ctaLink:[''],featuredServices:['']});
  readonly settingsForm=this.fb.group({siteNameEn:[''],siteNameAr:[''],addressEn:[''],addressAr:[''],email:[''],whatsapp:[''],phonesJson:['[]'],hoursJson:['[]'],socialJson:['[]'],seoTitleEn:[''],seoTitleAr:[''],seoDescriptionEn:[''],seoDescriptionAr:['']});
  readonly stats=[{key:'consultations',path:API.consultations,label:'',value:'—',note:''},{key:'articles',path:API.articles,label:'',value:'—',note:''},{key:'services',path:API.services,label:'',value:'—',note:''},{key:'users',path:API.users,label:'',value:'—',note:''}];
  private readonly colKeys:Record<string,[string,string][]>= {dashboard:[['name','column.client'],['service','column.service'],['preferredDate','column.requested'],['status','column.status']],users:[['name','column.name'],['email','column.email'],['role','column.role'],['isActive','column.status']],consultations:[['name','column.client'],['phone','column.phone'],['preferredDate','column.requested'],['status','column.status']],articles:[['title','column.title'],['category','column.category'],['status','column.status'],['createdAt','column.created']],services:[['title','column.title'],['shortDescription','column.summary'],['order','column.order'],['isActive','column.status']]};
  get title():string{return this.i18n.t(this.section==='dashboard'?'dashboard.title':this.createMode?'page.articles.create':`page.${this.section}.title`)}
  get description():string{return this.i18n.t(this.section==='dashboard'?'dashboard.description':`page.${this.section}.description`)}
  get columns():Column[]{return (this.colKeys[this.section]||[]).map(([key,label])=>({key,label:this.i18n.t(label)}))}
  get userName():string{try{return JSON.parse(localStorage.getItem('alsaiari.user')||'{}').name||''}catch{return ''}}
  ngOnInit():void{this.stats.forEach(s=>{s.label=this.i18n.t(`dashboard.${s.key}`);s.note=this.label('live')});this.load();this.search.valueChanges.subscribe(()=>{this.pageNumber=1;this.load()});if(this.section==='dashboard')this.loadStats();if(this.createMode)this.startCreate()}
  label(key:string):string{const ar:Record<string,string>={add:'إضافة جديد',edit:'تعديل',view:'عرض',back:'رجوع للقائمة',save:'حفظ التغييرات',saving:'جار الحفظ…',cancel:'إلغاء',confirmDelete:'هل تريد حذف هذا العنصر؟',search:'بحث...',title:'العنوان',shortDescription:'وصف مختصر',excerpt:'ملخص',description:'الوصف',category:'التصنيف',order:'الترتيب',status:'الحالة',active:'مفعل',image:'الصورة',currentImage:'الصورة الحالية:',bilingualHelp:'أدخل المحتوى باللغتين العربية والإنجليزية',hero:'القسم الرئيسي',subtitle:'العنوان الفرعي',buttonText:'نص الزر',buttonLink:'رابط الزر',about:'من نحن',cta:'دعوة لاتخاذ إجراء',ctaLink:'رابط الزر',featuredServices:'معرفات الخدمات المميزة (افصل بينها بفاصلة)',serviceIdsHint:'معرف الخدمة، معرف الخدمة',siteIdentity:'بيانات الموقع',siteNameEn:'اسم الموقع بالإنجليزية',siteNameAr:'اسم الموقع بالعربية',contactDetails:'بيانات التواصل',addressEn:'العنوان بالإنجليزية',addressAr:'العنوان بالعربية',email:'البريد الإلكتروني',whatsapp:'واتساب',phonesJson:'الهواتف (JSON)',workingHoursJson:'ساعات العمل (JSON)',socialLinksJson:'روابط التواصل الاجتماعي (JSON)',seo:'تحسين محركات البحث',seoTitle:'عنوان SEO',seoDescription:'وصف SEO',live:'بيانات محدثة من النظام',jsonInvalid:'تحقق من صحة تنسيق JSON'};const en:Record<string,string>={add:'Add new',edit:'Edit',view:'View',back:'Back to list',save:'Save changes',saving:'Saving…',cancel:'Cancel',confirmDelete:'Delete this item? This action cannot be undone.',search:'Search…',title:'Title',shortDescription:'Short description',excerpt:'Excerpt',description:'Description',category:'Category',order:'Display order',status:'Status',active:'Active',image:'Image',currentImage:'Current image:',bilingualHelp:'Enter content in both Arabic and English',hero:'Hero section',subtitle:'Subtitle',buttonText:'Button text',buttonLink:'Button link',about:'About section',cta:'Call to action',ctaLink:'Call to action link',featuredServices:'Featured service IDs (comma separated)',serviceIdsHint:'service id, service id',siteIdentity:'Site identity',siteNameEn:'Site name (English)',siteNameAr:'Site name (Arabic)',contactDetails:'Contact details',addressEn:'Address (English)',addressAr:'Address (Arabic)',email:'Email',whatsapp:'WhatsApp',phonesJson:'Phone numbers (JSON)',workingHoursJson:'Working hours (JSON)',socialLinksJson:'Social links (JSON)',seo:'Search engine optimization',seoTitle:'SEO title',seoDescription:'SEO description',live:'Live system data',jsonInvalid:'Please check the JSON format'};return (this.i18n.locale()==='ar'?ar:en)[key]||key}
  link(path:string):string{return `/${this.i18n.locale()}/${path}`}
  private endpoint():string{return ({users:API.users,consultations:API.consultations,articles:API.articles,services:API.services,dashboard:API.consultations} as Record<string,string>)[this.section]||''}
  load():void{if(this.section==='homepage'||this.section==='settings'){this.loadDetail();return}if(this.section==='notifications'){this.api.get<{items:Row[];pagination:unknown}>(API.notifications,{page:1,limit:30}).subscribe({next:r=>this.notifications=r.data.items,error:()=>this.notifications=[]});return}if(this.createMode||this.editorMode)return;this.loading=true;this.error='';this.api.get<{items:Row[];pagination:{page:number;total:number;totalPages:number}}>(this.endpoint(),{page:this.pageNumber,limit:this.section==='dashboard'?5:10,search:this.search.value||undefined}).pipe(finalize(()=>this.loading=false)).subscribe({next:r=>{this.rows=r.data.items;this.pagination=r.data.pagination},error:e=>this.error=e.error?.message||this.i18n.t('error.loadFailed')})}
  loadStats():void{for(const stat of this.stats)this.api.get<{items:Row[];pagination:{total:number}}>(stat.path,{page:1,limit:1}).subscribe({next:r=>stat.value=String(r.data.pagination.total),error:()=>stat.value='—'})}
  display(row:Row,key:string):string{let v=row[key];if(key==='title'||key==='shortDescription'||key==='category'){if(v&&typeof v==='object')v=v[this.i18n.locale()]||'—'}if(key==='isActive')return this.i18n.t(v===true?'table.active':'table.inactive');if(key==='service'&&v&&typeof v==='object'){const t=v.title;return t&&typeof t==='object'?String(t[this.i18n.locale()]||'—'):String(t||'—')}if(key==='status'&&typeof v==='string')return this.i18n.t(`status.${v}`)||v;return String(v??'—')}
  page(delta:number):void{this.pageNumber+=delta;this.load()}
  startCreate():void{this.editorMode='create';this.editId='';this.image=null;this.imageUrl='';this.error='';this.recordForm.reset({titleEn:'',titleAr:'',summaryEn:'',summaryAr:'',descriptionEn:'',descriptionAr:'',categoryEn:'',categoryAr:'',order:0,isActive:true,status:'draft'})}
  view(row:Row):void{this.openRecord(row,'view')}
  edit(row:Row):void{this.openRecord(row,'edit')}
  private openRecord(row:Row,mode:'view'|'edit'):void{this.loading=true;this.error='';const path=`${this.endpoint()}/${row['_id']}`;this.api.get<{service?:Row;article?:Row}>(path).pipe(finalize(()=>this.loading=false)).subscribe({next:r=>{const item=(r.data.service||r.data.article||row) as Row;this.editorMode=mode;this.editId=String(item['_id']);this.imageUrl=item.image?.url||item.featuredImage?.url||'';this.recordForm.reset({titleEn:item.title?.en||'',titleAr:item.title?.ar||'',summaryEn:(this.section==='services'?item.shortDescription?.en:item.excerpt?.en)||'',summaryAr:(this.section==='services'?item.shortDescription?.ar:item.excerpt?.ar)||'',descriptionEn:(this.section==='services'?item.description?.en:item.content?.en)||'',descriptionAr:(this.section==='services'?item.description?.ar:item.content?.ar)||'',categoryEn:item.category?.en||'',categoryAr:item.category?.ar||'',order:item.order??0,isActive:item.isActive??true,status:item.status||'draft'})},error:e=>this.error=e.error?.message||this.i18n.t('error.loadFailed')})}
  cancelEditor():void{if(this.createMode){this.router.navigateByUrl(this.link('admin/articles'));return}this.editorMode='';this.error='';this.load()}
  saveRecord():void{if(this.recordForm.invalid)return;this.saving=true;this.error='';const v=this.recordForm.getRawValue();const body:Row=this.section==='services'?{title:{en:v.titleEn,ar:v.titleAr},shortDescription:{en:v.summaryEn,ar:v.summaryAr},description:{en:v.descriptionEn,ar:v.descriptionAr},order:Number(v.order)||0,isActive:!!v.isActive}:{title:{en:v.titleEn,ar:v.titleAr},excerpt:{en:v.summaryEn,ar:v.summaryAr},content:{en:v.descriptionEn,ar:v.descriptionAr},category:{en:v.categoryEn,ar:v.categoryAr},status:v.status};let payload:unknown=body;if(this.image){const fd=new FormData();fd.append(this.section==='services'?'image':'featuredImage',this.image);for(const [k,val]of Object.entries(body))fd.append(k,JSON.stringify(val));payload=fd}const request=this.editId?this.api.put(`${this.endpoint()}/${this.editId}`,payload):this.api.post(this.endpoint(),payload);request.pipe(finalize(()=>this.saving=false)).subscribe({next:()=>{if(this.createMode){this.router.navigateByUrl(this.link('admin/articles'));return}this.editorMode='';this.load()},error:e=>this.error=e.error?.message||this.i18n.t('error.generic')})}
  selectImage(e:Event):void{this.image=(e.target as HTMLInputElement).files?.[0]||null}
  toggle(row:Row):void{if(this.section==='articles'){const status=row['status']==='published'?'draft':'published';this.api.patch(`${API.articles}/${row['_id']}/status`,{status}).subscribe({next:()=>this.load(),error:e=>this.error=e.error?.message||this.i18n.t('error.generic')});return}if(this.section==='services'){this.api.patch(`${API.services}/${row['_id']}/status`,{isActive:row['isActive']===false}).subscribe({next:()=>this.load(),error:e=>this.error=e.error?.message||this.i18n.t('error.generic')});return}this.api.patch(`${API.users}/${row['_id']}/status`,{isActive:row['isActive']===false}).subscribe({next:()=>this.load(),error:e=>this.error=e.error?.message||this.i18n.t('error.generic')})}
  confirmDelete():void{if(!this.pendingDelete)return;this.api.delete(`${this.endpoint()}/${this.pendingDelete['_id']}`).subscribe({next:()=>{this.pendingDelete=null;this.load()},error:e=>this.error=e.error?.message||this.i18n.t('error.generic')})}
  loadDetail():void{const path=this.section==='homepage'?API.homepage:API.settings;this.loading=true;this.error='';this.api.get<Row>(path).pipe(finalize(()=>this.loading=false)).subscribe({next:r=>{const d=(this.section==='homepage'?r.data.homepage:r.data.settings)||r.data;if(this.section==='homepage')this.homepageForm.reset({heroTitleEn:d.hero?.title?.en||'',heroTitleAr:d.hero?.title?.ar||'',heroSubtitleEn:d.hero?.subtitle?.en||'',heroSubtitleAr:d.hero?.subtitle?.ar||'',heroButtonEn:d.hero?.buttonText?.en||'',heroButtonAr:d.hero?.buttonText?.ar||'',heroLink:d.hero?.buttonLink||'',aboutTitleEn:d.about?.title?.en||'',aboutTitleAr:d.about?.title?.ar||'',aboutDescriptionEn:d.about?.description?.en||'',aboutDescriptionAr:d.about?.description?.ar||'',ctaTitleEn:d.cta?.title?.en||'',ctaTitleAr:d.cta?.title?.ar||'',ctaDescriptionEn:d.cta?.description?.en||'',ctaDescriptionAr:d.cta?.description?.ar||'',ctaButtonEn:d.cta?.buttonText?.en||'',ctaButtonAr:d.cta?.buttonText?.ar||'',ctaLink:d.cta?.buttonLink||'',featuredServices:(d.featuredServices||[]).map((x:any)=>typeof x==='string'?x:x._id).join(', ')});else this.settingsForm.reset({siteNameEn:d.siteName?.en||'',siteNameAr:d.siteName?.ar||'',addressEn:d.contact?.address?.en||'',addressAr:d.contact?.address?.ar||'',email:d.contact?.email||'',whatsapp:d.contact?.whatsapp||'',phonesJson:JSON.stringify(d.contact?.phones||[],null,2),hoursJson:JSON.stringify(d.workingHours||[],null,2),socialJson:JSON.stringify(d.socialLinks||[],null,2),seoTitleEn:d.seo?.defaultTitle?.en||'',seoTitleAr:d.seo?.defaultTitle?.ar||'',seoDescriptionEn:d.seo?.defaultDescription?.en||'',seoDescriptionAr:d.seo?.defaultDescription?.ar||''})},error:e=>this.error=e.error?.message||this.i18n.t('error.loadFailed')})}
  saveSingleton(which:'homepage'|'settings'):void{this.saving=true;this.error='';let body:Row;if(which==='homepage'){const v=this.homepageForm.getRawValue();body={hero:{title:{en:v.heroTitleEn,ar:v.heroTitleAr},subtitle:{en:v.heroSubtitleEn,ar:v.heroSubtitleAr},buttonText:{en:v.heroButtonEn,ar:v.heroButtonAr},buttonLink:v.heroLink},about:{title:{en:v.aboutTitleEn,ar:v.aboutTitleAr},description:{en:v.aboutDescriptionEn,ar:v.aboutDescriptionAr}},cta:{title:{en:v.ctaTitleEn,ar:v.ctaTitleAr},description:{en:v.ctaDescriptionEn,ar:v.ctaDescriptionAr},buttonText:{en:v.ctaButtonEn,ar:v.ctaButtonAr},buttonLink:v.ctaLink},featuredServices:(v.featuredServices||'').split(',').map(x=>x.trim()).filter(Boolean)}}else{const v=this.settingsForm.getRawValue();try{body={siteName:{en:v.siteNameEn,ar:v.siteNameAr},contact:{address:{en:v.addressEn,ar:v.addressAr},email:v.email,whatsapp:v.whatsapp,phones:JSON.parse(v.phonesJson||'[]')},workingHours:JSON.parse(v.hoursJson||'[]'),socialLinks:JSON.parse(v.socialJson||'[]'),seo:{defaultTitle:{en:v.seoTitleEn,ar:v.seoTitleAr},defaultDescription:{en:v.seoDescriptionEn,ar:v.seoDescriptionAr}}}}catch{this.error=this.label('jsonInvalid');this.saving=false;return}}this.api.put(which==='homepage'?API.homepage:API.settings,body).pipe(finalize(()=>this.saving=false)).subscribe({next:()=>this.loadDetail(),error:e=>this.error=e.error?.message||this.i18n.t('error.generic')})}
  read(item:Row):void{this.api.patch(`${API.notifications}/${item['_id']}/read`).subscribe({next:()=>item['isRead']=true,error:()=>undefined})}
  markAll():void{this.api.patch(`${API.notifications}/read-all`).subscribe({next:()=>this.notifications.forEach(n=>n['isRead']=true),error:()=>undefined})}
}
